### ISSUE TITLE
meow-last-buffer

### ISSUE THREAD

**Issue by KiteAB** [DogLooksGood/meow#18]
If in a selection, then cancel all selection, if not then switch to last buffer, Do you think it's better than before?

**Comment by DogLooksGood** [comment]
You can just have this behavior.

First of all, there's a command `meow-cancel-selection`, since cancel selection is only useful when there is a selection, so it support user-customized fallback behavior.

Variable `meow-selection-command-fallback` is used to specify fallback command for those selection-only commands. Add this to the list, then bind `meow-cancel-selection` to <kbd>esc</kbd> with `meow-normal-define-key`.

```
(meow-cancel-selection . meow-last-buffer)
```

**Comment by KiteAB** [comment]
k, I already have a humble personal solution for this issue:
```emacs-lisp
(defun kiteab/meow-last-buffer ()
  (interactive)
  (if (region-active-p)
      (deactivate-mark t)
    (meow-last-buffer nil)))
```
You can close this issue after updating the document, this is just a small opinion.

**Comment by DogLooksGood** [comment]
doc updated.

**Comment by DogLooksGood** [comment]
You can always use `call-interactively` to invoke another command, in this way, prefix arguments is preserved.
