### ISSUE TITLE
Integrate with which-key

### ISSUE THREAD

**Issue by koleiskiy** [DogLooksGood/meow#2]
When `SPC x` is pressed, `which-key` does not show keybindings even though `which-key` is enabled.

Do you have any plan to integrate with `which-key`?

**Comment by DogLooksGood** [comment]
`KEYPAD` state is using the same idea from god-mode. `which-key` has a support for `god-mode`, I think it's possible to port into Meow. 

I'll give a try.

**Comment by DogLooksGood** [comment]
I've finished refactoring, I reconsidered about integrate with `which-key`, since Meow is encourage users not to build a complex leader map, and those `C-x` and `C-c` are lacking descriptions for each steps. So the which-key won't help too much in our case, so I decided to not integrate with which-key.

**Comment by mclearc** [comment]
I wonder if you might reconsider this? It isn't about building complex maps. Rather, it is about not interrupting existing workflows. I use which key, and display it in a buffer at the top of the frame. Meow displays keybindings at the bottom. I'd prefer not to spit things in this way. Ideally there would be an option to just let which key handle all keybinding displays. I'm not sure why meow would insist on doing this itself.

**Comment by DogLooksGood** [comment]
Hi @mclearc,
It's possible to provide a function to meow, to tell meow how keymap description popup should be displayed.

The variable is called `meow-keypad-describe-keymap-function`,the value is a function receive one argument, a keymap. This function is called whenever meow tries to display a popup. 

The default value of this variable is `meow-describe-keymap`.

So probably you can do it with which-key, but  I did some quick search in which-key before I write current implementation. I can't find a public function for this (or I'm not aware of it), nor I can wrap some function easily for this.

**Comment by DogLooksGood** [comment]
After the keypad refactor, we have the ability to integrate with which-key. 
Now if which-key is enabled, meow will use which-key popup instead of the builtin one.
However, which-key provides alias titles based on input, and in keypad, the input is different from the one in vanilla Emacs.

![image](https://user-images.githubusercontent.com/11796018/150699006-49f5afb5-e58b-481d-8c3c-33a1612d23f3.png)

If you want something like `+toggle-map` in which-key popup(shown above), it's still necessary to use keymap alias.
Otherwise, only `+prefix` will be displayed.

**Comment by mclearc** [comment]
Thanks for the which-key integration! One way to work around the `prefix` issue that you describe is to use something like `bind-key` to state custom keymaps. So for example, I have the map:

```emacs-lisp
(bind-keys :prefix-map cpm+file-keys
           :prefix (concat cpm-prefix " f")
           ("b" . consult-bookmark                 )
           ("f" . find-file                        )
           ("l" . consult-locate                   )
           ("o" . crux-open-with                   )
           ("s" . save-buffer                      )
           ("r" . consult-recent-file              )
           ("y" . cpm/show-and-copy-buffer-filename))
```

And if I put this in `  (meow-leader-define-key)` like so:

```emacs-lisp
  (meow-leader-define-key
   '("f" . cpm+file-keys))
```

the name shows up correctly in the which-key popup.
