### ISSUE TITLE
[suggestion] make `meow-find` and `meow-till` respect `meow-reverse`?

### ISSUE THREAD

**Issue by moesasji** [DogLooksGood/meow#38]
This might just be one of the cases of needing to get used to the most efficient way to work with `meow`, but I find it surprising that the commands relating to `meow-find` and `meow-till` do not respect `meow-reverse` in the same way as happens for `meow-block` and `meow-line`. Effectively I'm missing what in vim are the `f/F` and `t/T` pairs of bindings.

I see that some of the [backwards operations](https://github.com/DogLooksGood/meow/blob/c29239b66e70068d8027d13f83e0112b32de07eb/meow-command.el#L1158) for `meow-find` and `meow-till` are in the code, but adding those would take additional bindings. 

Would it be a good idea to have the `meow-till` and `meow-find` operations (and the expand variants) respect `meow-reverse` binding so that one can also search for characters backward without needing to bind additional keys?

**Comment by DogLooksGood** [comment]
Hi, you can have a backward find/till with `negative-argument`, so you have <kbd>-f</kbd> for backward find. Since you can bind negative argument command to whatever key you like, It's not harder to type than <kbd>F</kbd>. Both require two keys.

And why they don't respect reverse selection, there are some rules in design.
1. A selection type can be described as `expand/select` + `type of thing`(i.e `line`).
2. If current command have the same `type of thing` with current selection, and the selection is an `expand` selection, it will respect the direction and expand the selection.

`meow-line` and `meow-block` will create `expand line` and `expand block`.

**Comment by moesasji** [comment]
> My cat close the issue, I reopened it, feel free to ask anything if it's not make sense.

Your explanation makes perfect sense, although I'm a bit less enthusiastic to use `-` for this. Essentially in my layout I have shift on the thumb, while `-`  is a reach making it far less pleasant to type. :-(

However I wonder whether you've actually stumbled on  a solution for the fact that in the kakoune editing modal you loose a lot of keys compared to vim as in the kakoune model you need the same letter needed for both motion and expand. This friction is actually visible in your use of `word` and `symbol` where suddenly the capitalized version does not expand (and I have to hit a number to do it). That problem is hard to work around as you want both of these on good keys for people that program. So effectively you opted for the solution that in that case the loss of the idea what the role of the capital version of a letter does is worth it.

The idea you have with the direction of motion being persistent with some of the operations might to be a potential way around this as one could use that same concept for all `things/objects` without having to keep typing the extra `-` for every time you want to do the operation backward. Depending on what direction of motion is active you either go forward or backward for the same key. 

btw) The response is just food for thought triggered by first impressions.

**Comment by DogLooksGood** [comment]
Kakoune has a great consistency on command layout. It use x, alt-x, shift-x, alt-shift-x, for forward, backward, forward expand and backward expand. But I want to avoid modifiers as much as possible. So my approach is to separate commands into three groups depends on command frequencies. 

# The basic character movement
This includes `left`, `right`, `prev` and `next`. They are most frequently used. Same behavior on every editors.

# Word / Symbol
Word and symbol are frequently used, so I want a first class support for backward movement. This require us have both `next-word` and `back-word`. What about expanding? We introduce another command `mark-word`, this command gives us a selection with type `expand word`. Now you can use `next-word` and `back-word` for expanding.

# Other movements.
You already know these commands, one command for one thing. Use `negative-argument` for backward. 


In Meow, you can define your own layout. If you have `negative-argument` on left hand, you can put possible following commands on right hand.

**Comment by moesasji** [comment]
The thing that I'm trying to say is that from reading the purpose of the `reverse` was pretty unclear, but when trying it out I find using it very intuitive for the block and line commands. If the operation is intuitive for those commands I just wondered if that can be exploited as a more general pattern.

Think of the analogy of walking: if you want to walk back you turn around and then walk forward (in that direction). That line of thinking would be one route to get more fundamental commands on keys while sticking to `shift` is `expand` without having to resort to the modifiers.

btw) Note that from your response I see that you use `mark-word/mark-symbol` to start expanding with words/symbols. I hadn't spotted that trick!

btw2) I fully agree with your wish on wanting to avoid the modifiers, but can also see why kakoune had to resort to it, i.e. only having 26 characters isn't really enough for the frequent commands.

**Comment by DogLooksGood** [comment]
In Emacs, it's possible to have no selection, if you don't have one, you can't reverse. You may thinking use a variable to indicate that next command should be reversed. I think this approach make things complex. I want `meow-reverse` is just as simple as `exchange-point-and-mark`.  

You may also noticed previous selection will be cancelled when you starting another with new selection type. If you have a reversed word selection at the moment, and you want to select the next block, you don't have to reverse, just use `meow-block`. Or if you want to select the pervious block, if doesn't matter current selection is forward or backward. Just use `negative-argument`.

Meow try not include Do-What-I-Mean style commands, DWIM commands is complex IMO. But it's possible to give a fallback behavior to a command that have effect only when there's a selection. Because `negative-argument` is really frequently used in meow, you may want to customize `meow-selection-command-fallback` to let `meow-reverse` fallback to `negative-argument` when there's no selection.

**Comment by moesasji** [comment]
Thanks for the extensive insight as this has clarified some of the things I had not grasped in how to best use `meow`

I find the read-me actually pretty clear; just a case of my pre-conceptions based on other modal packages turning out to be wrong. I had for example wrongly associated `mark-word` with the way `objed` uses that term. My mistake!

Issue can be closed as I had the wrong end of the stick and should just learn to properly use `negative-argument` ;)

**Comment by DogLooksGood** [comment]
When I have time, I may restructure document a little bit, add more gifs to make it more readable.

**Comment by DogLooksGood** [comment]
![6d5a5d597d7bab53532abb55eaae2200f1d1e240_2_1120x1000](https://user-images.githubusercontent.com/11796018/110201635-16105100-7e9f-11eb-891f-b422b01e9bb8.png)

Now I have this graph for command relations, WIP
