### ISSUE TITLE
some questions about using meow

### ISSUE THREAD

**Issue by ginhton** [DogLooksGood/meow#42]
First, thank you guys for developing such a brilliant operation mode for editing. It boosts my daily editing! 
I have some questions about using meow, and any suggestions is appreciated.
   - In fact, yank means copy, and paste means paste. But in your documentation, p means yank and y means save. I think you may misuse yank in your command name.
   - How to disable popup of key hints? (如何禁用关于按键的提示呢?) For example, I pressed `space x c`, and will press `f`, here a popup menu appears at the bottom showing the available command. How to disable this popup menu?
   - Is there something like '(evil-escape-key-sequence "tn")? When I press `tn` quickly in INSERT mode, I will return to NORMAL mode.

**Comment by DogLooksGood** [comment]
Hi, thanks for the nice words! :)

> In fact, yank means copy, and paste means paste. But in your documentation, p means yank and y means save. I think you may misuse yank in your command name.

Command names in Vim and Emacs are quite different. In Emacs, by default, you use <kbd>C-y</kbd> to paste, and this command is `yank`, It means "召回", it yank an item from `kill-ring` which you can think it's the clipboard in Emacs(but there are some differences). And the copy command in Emacs is `kill-ring-save`. Since Meow is an Emacs package, so we follow the Emacs tradition, use `yank` and `save`(shorten for kill-ring-save).

> How to disable popup of key hints? (如何禁用关于按键的提示呢?) For example, I pressed space x c, and will press f, here a popup menu appears at the bottom showing the available command. How to disable this popup menu?

Use `(setq meow-keypad-describe-keymap-function nil)`.

> Is there something like '(evil-escape-key-sequence "tn")? When I press tn quickly in INSERT mode, I will return to NORMAL mode.

No, there isn't one, but you can use [key-chord](https://github.com/emacsorphanage/key-chord) to get the same effect. Just bind a key sequence to `meow-insert-exit`.

**Comment by ginhton** [comment]
Thank you for quick and patient responce!
With your suggestions, I make meow more easy to use with my editing habit!
At last, thank you for your hard working! I hope this project can become better and better!
