### ISSUE TITLE
Why is MOTION mode named MOTION?

### ISSUE THREAD

**Issue by harryfei** [DogLooksGood/meow#67]
I'm just curious.

**Comment by DogLooksGood** [comment]
Hi,

In general, MOTION mode usually provides some keybindings for motions. 

In evil, MOTION mode remaps only few motion keys, like J/K, to unify the cursor motion experience. 

In Meow, it's the same. If you are using J/K to move cursor down/up, you would like to bind J/K in MOTION mode. But if you use N/P, you don't have to bind, since that's the default behavior in Emacs.

**Comment by harryfei** [comment]
Thank you!
